config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
          controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"}
          # Add controller for registrations
  root to: 'pages#home'


  resources :mannequins, only: [:show, :index] do
    resources :attachinary_files, :path => "photos"
  end
  # change resources to sg!, the mannequin con only update itself, not other mannequins
  resource :mannequin, only: [:edit, :update]

  resource :client, only: [:show, :edit, :update] do
    resource :photo_shooting, only: [:show, :new, :create, :destroy]
  end
  get "/page/mannequin/women" => "pages#women"
  get "/page/mannequin/men" => "pages#men"
  get "/page/mannequin/" => "pages#search"
  get "page/contact" => 'pages#contact'

  mount Attachinary::Engine => "/attachinary"

end

app/models/mannequin.rb
class Mannequin < ActiveRecord::Base
  @@hair_color = ["Blond", "Brunnette", "Red Hair", "Auburn", "Black"]
  @@ethnicity = %w(caucasian asian black american francais)
  @@category = ["beaute", "haute-couture", "atypique", "new-face", "hipster"]

  belongs_to :user
  has_many :attachinary_files
  has_many :photo_shootings
  has_many :clients, through: :photo_shootings

  validates :age, presence: true, on: :update
  has_attachments :photos

  def self.hair_color
    @@hair_color
  end

  def self.ethnicity
    @@ethnicity
  end

  def self.category
    @@category
  end

end

app/controllers/mannequins_controller.rb
class MannequinsController < ApplicationController
  before_action :set_mannequin, only: [:edit, :update, :destroy]
  before_action :desauthorize_client, only:[:edit]
  # A visitor can view each mannequin's profile
  skip_before_action :authenticate_user!, only: [:show, :index]
  # GET /mannequins
  # GET /mannequins.json
  def index
    @mannequins = Mannequin.all
  end

  # GET /mannequins/1
  # GET /mannequins/1.json
  def show
    @mannequin = Mannequin.find(params[:id])

    @photo_shooting = @mannequin.photo_shootings.build()
    # this disables the header and footer on this specific pages
    @disable = true
  end

  # GET /mannequins/edit
  def edit
  end

  # PATCH/PUT /mannequins/1
  # PATCH/PUT /mannequins/1.json
  def update
    respond_to do |format|
      if @mannequin.update(mannequin_params)

        format.html { redirect_to @mannequin, notice: 'Mannequin was successfully updated.' }
        format.json { render :show, status: :ok, location: @mannequin }
      else
        format.html { render :edit }
        format.json { render json: @mannequin.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mannequin
      @mannequin = current_user.mannequin
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mannequin_params
      # here the photos need to be at the end for some mystic reasons
      params.require(:mannequin).permit(:first_name, :last_name, :phone, :age, :location, :category, :description, :height, :waist, :chest, :hips, :hair_color, :eyes, :ethnicity, photos: [])
    end

    def desauthorize_client
    # If the current user is not a client, he gets redirected to the root page
    if !current_user.mannequin
      redirect_to root_path, alert: "You don't have the rights"
    end
  end
end

app/helpers/mannequins_helper.rb
module MannequinsHelper
end

app/views/mannequins/_form.html.erb
<!-- add url for the update, so that the update targets the correct place -->

  <%= simple_form_for current_user.mannequin, url: '/mannequin' do |m| %>

    <%= m.error_notification %>

    <div class="form-inputs">
      <%= m.input :first_name, placeholder: "Enter your first name: " %>
      <%= m.input :last_name, placeholder:"Enter your last name: " %>
      <%= m.input :phone %>

      <%= m.input :age, placeholde: 'dob' %>
      <%= m.input :gender, collection: ["women", "men"], prompt: "Select your gender" %>
      <%= m.input :category, collection: ["beaute", "haute-couture", "atypique", "new-face", "hipster"], prompt: "Select your category" %>
      <%= m.input :description, as: :text %>
      <%= m.input :height, placeholder: "Please enter in cm " %>
      <%= m.input :waist, placeholder: "Please enter in cm " %>
      <%= m.input :chest,placeholder: "Please enter in cm " %>
      <%= m.input :hips, placeholder: "Please enter in cm " %>
      <%= m.input :hair_color, collection: Mannequin.hair_color, prompt: "Select your hair color" %>
      <%= m.input :eyes %>
      <%= m.input :ethnicity, collection: ["Caucasian", "Asian", "African", "Hispanic", "Metisse"], prompt: "Select your Ethnicity" %>
      <%= m.input :location, placeholder: "City "%>
      <%= m.label 'Email: ', current_user.email, class: "form-mannequin-email" %>
    </div>

  <div class="form-actions">
    <%= m.button :submit, "Save", class: "btn btn-treehouse", style: "margin-top: 20px;" %>
  </div>

<% end %>

app/views/mannequins/edit.html.erb
<h1><%= current_user.mannequin.first_name %></h1>

<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-2 col-xs-offset-5 text-center">
        <button class="btn btn-white-category"><%= link_to 'Profile', mannequin_path(current_user.mannequin), target: "_blank", style: "text-decoration: none; color: black;" %></button>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="text-center">
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title text-center">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
           aria-expanded="true" aria-controls="collapseOne">
          Info
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="text-center">
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
              <h4 class="panel-title text-center">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"
                aria-expanded="false" aria-controls="collapseTwo">
                Photos
              </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
              <%= render 'attachinary_files/form' %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-2 col-xs-offset-5">
    <div class="text-center">
      <button class="btn btn-white-category" style="margin-bottom: 20px;"><%= link_to 'Back', mannequins_path, style: "text-decoration: none; color: black" %></button>
    </div>
  </div>
</div>

app/views/mannequins/index.html.erb
<p id="notice"><%= notice %></p>


<div class="index-wrapper">
  <h1> Mannequins </h1>
  <br>
  <p>Results: (<%= @mannequins.count %>)</p>
  <div class="container">
    <div class="row">
      <% @mannequins.each do |m| %>
        <div class="col-sm-6 col-md-3">
          <div class="mannequin-card">
          <!-- link_to not working properly -->
          <p><%= link_to mannequin_path(m) do %>
            <%= cl_image_tag m.photos[0].path, width: 200, height: 200, crop: :fill %>
            <div> <%= "#{m.first_name + " " + m.last_name[0] + "."}" %> </div>
            <% end %>
          </div>
        </p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/mannequins/show.html.erb
<!-- this is used to give a class to the body -->
<% @body_class="show" %>

<div id="deskopt-show">
  <div class="profile-wrapper">
    <div class="profile-header">
      <div class="profile-name-description">
        <div><h1><%= @mannequin.first_name %> <%= @mannequin.last_name %></h1></div>
        <div class="description"><%= @mannequin.description %></div>
      </div>
      <div class="profile-location"><p>Available in <%= @mannequin.location %> <i class="fa fa-map-marker" aria-hidden="true"></i> <i class="fa fa-heart-o" aria-hidden="true"></i></p>
      </div>
    </div>
    <div class="profile-main">
      <div class="profile-user-info">
        <ul class="list-unstyled">
          <li><p><b> Heights</b></p>
            <p><%= @mannequin.height %></p>
          </li>
          <li><p><b> Chest</b></p>
            <p><%= @mannequin.chest %></p></li>
            <li><p><b> Waist</b></p>
              <p><%= @mannequin.waist %></p></li>
              <li><p><b> Hips</b></p>
                <p><%= @mannequin.hips %></p>
              </li>
              <li><p><b> Hair</b></p>
                <p><%= @mannequin.hair_color %></p>
              </li>
              <li><p><b> Eyes</b></p>
                <p><%= @mannequin.eyes %></p>
              </li>
              <li><p><b> Origins</b></p>
                <p><%= @mannequin.ethnicity %></p>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-4">
            <div class="profile-photos">
              <% @mannequin.photos.each do |photo| %>
              <%= cl_image_tag photo.path, width: 600, crop: :fill %>
              <% end %>
               <div class="row">
          <div class="col-xs-12">
            <%= render 'photo_shootings/form' %>
          </div>
        </div>
      </div>
    </div>
            </div>
          </div>
        </div>


    <div id="mobile-show">
      <div><h1><%= @mannequin.first_name %> <%= @mannequin.last_name %></h1></div>
      <hr>
      <div class="profile-location"><p>Available in <%= @mannequin.location %> <i class="fa fa-map-marker" aria-hidden="true"></i> <i class="fa fa-heart-o" aria-hidden="true"></i></p>
      </div>
      <hr>
      <div class="profile-main">
        <div class="profile-user-info">
          <div class="list-unstyled">
            <span><p><b> Heights</b></p>
              <p><%= @mannequin.height %></p>
            </span>
            <span><p><b> Chest</b></p>
              <p><%= @mannequin.chest %></p></span>
              <span><p><b> Waist</b></p>
                <p><%= @mannequin.waist %></p></span>
                <span><p><b> Hips</b></p>
                  <p><%= @mannequin.hips %></p>
                </span>
                <span><p><b> Hair</b></p>
                  <p><%= @mannequin.hair_color %></p>
                </span>
                <span><p><b> Eyes</b></p>
                  <p><%= @mannequin.eyes %></p>
                </span>
                <span><p><b> Origins</b></p>
                  <p><%= @mannequin.ethnicity %></p>
                </span>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="profile-photos">
                  <% @mannequin.photos.each do |photo| %>
                  <%= cl_image_tag photo.path, width: 600, crop: :fill %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>