config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
          controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"}
          # Add controller for registrations
  root to: 'pages#home'


  resources :mannequins, only: [:show, :index] do
    resources :attachinary_files, :path => "photos"
  end
  # change resources to sg!, the mannequin con only update itself, not other mannequins
  resource :mannequin, only: [:edit, :update]

  resource :client, only: [:show, :edit, :update] do
    resource :photo_shooting, only: [:show, :new, :create, :destroy]
  end
  get "/page/mannequin/women" => "pages#women"
  get "/page/mannequin/men" => "pages#men"
  get "/page/mannequin/" => "pages#search"
  get "page/contact" => 'pages#contact'

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container" id="mobile-footer">
  <div class="container" id="footer">
    <div class="text-center">
    <div class="row">
        <div class="col-xs-12">
        <p> <%= link_to 'Catalog', '#'  %> / <%= link_to 'Join Dyna', '#' %> / <%= link_to 'Contact', '#' %> / <%= link_to 'FAQ', '#' %></p>
        </div>
        <div class="col-xs-12">
          <p> <a href="#">Legal stuff</a> / <a href="#">Presse</a> / <a href="#"> Blog </a> / <a href="#">Jobs</a> </p>
        </div>
        <div class="col-xs-12" >
          <h4>Write Us</h4>
          <%= link_to 'contact@dynamodel.co', 'mailto:contact@dynamodel.co' %>
          <p>59 rue des Archives, 75003, Paris</p>
        </div>
        <div class="col-xs-12">
           <span class="li-social"><a href="https://www.instagram.com/dyna_model/" target="_blank"> <%= image_tag "socials/instagram.png"  %> </a> </span>
            <span class="li-social"><a href="https://www.twitter.com/dynamodel/" target="_blank"> <%= image_tag "socials/twitter.png"  %> </a></span>
            <span class="li-social"><a href="https://www.facebook.com/dynamodel/" target="_blank"> <%= image_tag "socials/facebook.png"  %> </a></span>
        </div>
        <div class="col-xs-12">
          <%= link_to "https://itunes.apple.com/fr/app/dynamodel/id1061702407?mt=8" do %>
            <h4>Are you a model? <br> Download the app here</h4>
            <%= image_tag 'appstore.png' %>
          <% end %>
        </div>
        <div class="col-xs-12">
          <h4>Dyna Newsletter</h4>
          <p>TODO</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer-container" id="deskopt-footer">
  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <!-- social icons -->
          <ul class="socials list-unstyled">
            <li class="li-social"><a href="https://www.instagram.com/dyna_model/" target="_blank"> <%= image_tag "socials/instagram.png"  %> </a> </li>
            <li class="li-social"><a href="https://www.twitter.com/dynamodel/" target="_blank"> <%= image_tag "socials/twitter.png"  %> </a></li>
            <li class="li-social"><a href="https://www.facebook.com/dynamodel/" target="_blank"> <%= image_tag "socials/facebook.png"  %> </a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h4>PLAN DU SITE</h4>
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><p>Catalogue</p></li>
              <li><p>Contact</p></li>
              <li><p>Candidature</p></li>
              <li><p><a href="blog.dynamodel.co">Blog</a> </p></li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><p> Presse</p></li>
              <li><p> Faq</p></li>
              <li><p> Jobs</p></li>
              <li><p> Mentions Légale</p></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div>
            <h4>Are you a model? Download the app here</h4>
          </div>
          <div>
            <%= link_to "https://itunes.apple.com/fr/app/dynamodel/id1061702407?mt=8" do %>
            <%= image_tag 'appstore.png' %>
            <% end %>
          </div>
        </div>
        <div class="col-md-3">
          <div> <h4>Write us</h4></div>
          <div><p> <%= link_to 'contact@dynamodel.co', "mailto:contact@dynamodel.co" %> </p> </div>
          <div> <p>59 rues des archives, 75003, Paris</p></div>

          <div>
           <h4>Dyna Newsletter</h4>
            <p> TO DO</p>
          </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-black">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-black-brand brand-xs" do %>
    <%= image_tag "dynamodel-black.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-black-right hidden-xs hidden-sm">

    <%= link_to "Women", page_mannequin_women_path%>
    <%= link_to "Men", page_mannequin_men_path%>
    <%= link_to "Join Dyna", new_user_registration_path %>
    <%= link_to "Contact", page_contact_path%>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-black-item navbar-black-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-black-item">
        <div class="dropdown">
          <% if user_signed_in? && current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: " navbar-black-menu", "data-toggle" => "dropdown" %>
          <% else  %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id:"navbar-black-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-black-dropdown-menu">
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <% if current_user.mannequin %>
              <li>
            <!-- mannequin can only see self (notice sg, no id get's passed) -->
                <%= link_to mannequin_path(current_user.mannequin), target: "_blank" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
            <% else %>
              <li>
            <!-- client can only edit self (notice sg, no id get's passed) -->
                <%= link_to client_path do %>
                  <i class="fa fa-user"></i>  <%= t(".profile", default: "Profile") %>
                <% end %>
             </li>
            <% end %>
            <% if current_user.mannequin %>
              <li>
            <!-- mannequin can only edit self (notice sg, no id get's passed) -->
             <%= link_to edit_mannequin_path do %>
                <i class="fa fa-pencil"></i>  <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <% else %>
              <li>
            <!-- client can only edit self (notice sg, no id get's passed) -->
             <%= link_to edit_client_path do %>
                <i class="fa fa-pencil"></i>  <%= t(".profile", default: "Edit Profile") %>
              <% end %>
             </li>
            <% end %>
            <li>
              <%= link_to "/users/edit" do %>
                <i class="fa fa-cog"></i>  <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-black-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-black-dropdown-menu">
        <li><a href="#">Women</a></li>
        <li><a href="#">Men</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">How to use</a></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>