config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
          controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"}
          # Add controller for registrations
  root to: 'pages#home'


  resources :mannequins, only: [:show, :index] do
    resources :attachinary_files, :path => "photos"
  end
  # change resources to sg!, the mannequin con only update itself, not other mannequins
  resource :mannequin, only: [:edit, :update]

  resource :client, only: [:show, :edit, :update] do
    resource :photo_shooting, only: [:show, :new, :create, :destroy]
  end
  get "/page/mannequin/women" => "pages#women"
  get "/page/mannequin/men" => "pages#men"
  get "/page/mannequin/" => "pages#search"
  get "page/contact" => 'pages#contact'

  mount Attachinary::Engine => "/attachinary"

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :photo_shootings
  has_many :mannequins, through: :photo_shootings

  # validates :company_name, presence: true
  # validates :website, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  # before_action :find_client, only: [:edit, :show]
  before_action :set_client, only: [:show, :edit, :update]
  before_action :desauthorize_mannequin, only: [:edit]

  def show
  end

  # def new
  #   @client = Client.new
  # end

  # def create

  #   if @client.save
  #     redirect_to client_path(@client)
  #   else
  #     render :new
  #   end
  # end

  def edit
    # @client = Client.new
  end

  def update
    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      render :edit
    end
  end


  private

  def set_client
    # @client = Client.new(client_params)
    @client = current_user.client
  end

  def find_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:company_name, :website, :first_name, :last_name, :phone, :email) #how to pass user_id
  end

  def desauthorize_mannequin
    # If the current user is not a client, he gets redirected to the root page
    if !current_user.client
      redirect_to root_path, alert: "You don't have the rights"
    end
  end

end

app/views/clients/edit.html.erb
<div class="edit-client-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="gray-box">
          <h1>Edit your profile</h1>
          <%= simple_form_for(current_user.client) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :first_name%>
              <%= f.input :last_name%>
              <%= f.input :company_name %>
              <%= f.input :website %>
            </div>

            <div class="form-actions">
             <%= f.button :submit, "Save", :class => "btn-base btn-gray btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <h1>Add your information</h1>

      <%= simple_form_for(@client) do |f| %>
        <%= f.error_notification %>
       <!--  <%= f.object.errors.full_messages %> -->

        <p>
          <%= f.input :company_name, placeholder: "your company"%>
        </p>

        <p>
        <%= f.input :website, placeholder: "your company website"%>
        </p>

        <%= f.button :submit, class:"btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="client-show-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="gray-box">
          <h1><%= @client.company_name%></h1>
          <br>
          <h4> <%= link_to "#{@client.website}", "http://#{@client.website}" %></h4>
          <h4>Name: <%= @client.first_name %></h4>
          <h4>Last name: <%= @client.last_name %></h4>
          <br>
          <%= link_to "Search", page_mannequin_path, :class => "btn-gray btn-base" %>
          <%= link_to "Home", root_path, :class => "btn-gray btn-base" %>
          <br>
          <p><%= link_to "Edit", edit_client_path %><p>
        </div>
      </div>
    </div>
  </div>
</div>